### ISSUE TITLE
json format of bucket lifecycles

### ISSUE THREAD

**Issue by dberardo-com** [rzrbld/adminio-ui#28]
Hi,

following this guide i am trying to setup retention policies for a minio bucket: 

https://docs.min.io/docs/minio-bucket-lifecycle-guide.html

in the example above they use JSON as a format to define a lifecycle, but adminio-ui only accepts .lifecycle or .xml files. IS it possible to expand it to JSON?

what is a .lifecycle format and how to convert JSON into it?

thank you

**Comment by rzrbld** [comment]
@dberardo-com  hi, by now adminio allow lifecycle config only in `.xml` format, which is ok since in general lifecycles - is [xml](https://github.com/minio/mc/blob/7e19044d982c42ab670d1b9124fd417019eadda4/cmd/ilm-import.go), aws or minio `json-representation` is for `cli` import/export operations. 

Any way i will implement import lifecycles in json format at weekend. Thank you for suggestion.
